# Generated by Django 3.2 on 2021-10-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('AGE', models.IntegerField()),
                ('DESCRIPTION', models.TextField()),
                ('DATE_ENROLLED', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
