# Generated by Django 3.2 on 2021-10-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='AGE',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='DATE_ENROLLED',
            new_name='date_enrolled',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='DESCRIPTION',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='NAME',
            new_name='name',
        ),
    ]
